version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5001:5432
    environment:
      - POSTGRES_DB=postings
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=myuser
