version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=users
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=myuser
