version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mapassword
      - POSTGRES_USER=mauser
      - POSTGRES_DB=madatabase
